### ISSUE TITLE
Elasticsearch 5.x issue on reindex `catalogsearch_fulltext`  : Illegal dynamic template parameter: [match_mapping]

### ISSUE THREAD

**Issue by andkirby** [magento/magento2#13995]
### Preconditions

Magento 2.2.3
MySQL - Percona 5.7

1. Wake up docker container elasticsearch 5.6.x (tested on 5.6.3)
we used following config:
1.1. `Dockerfile`
```
FROM elasticsearch:5.6
COPY config ./config
RUN chown -hR elasticsearch:elasticsearch ./config
```

1.2. `config/elasticsearch.yml`
```
network.host: 0.0.0.0
bootstrap.memory_lock: true
```
1.3. `config/logging.yml`
```
# you can override this using by setting a system property, for example -Des.logger.level=DEBUG
es.logger.level: INFO
rootLogger: ${es.logger.level}, console
logger:
  # log action execution errors for easier debugging
  action: DEBUG
  # reduce the logging for aws, too much is logged under the default INFO
  com.amazonaws: WARN

appender:
  console:
    type: console
    layout:
      type: consolePattern
conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"
```
1.4. Service `docker-compose.yml` config:
```
  elasticsearch:
    container_name: 'project-elasticsearch'
    build:
      context: ./elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    expose:
      - '9200'
```
2. Test it from docker app container:
```
$ curl -i http://elasticsearch:9200/_cluster/health
HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 392

{"cluster_name":"elasticsearch","status":"yellow","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":10,"active_shards":10,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":10,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":50.0}
```

### Steps to reproduce

1. Enable elastic search
```
magento config:set catalog/search/engine elasticsearch
magento config:set catalog/search/elasticsearch_server_hostname elasticsearch
```
2. Run reindex:
```
magento indexer:reindex catalogsearch_fulltext
``` 
or full reindex: `magento indexer:reindex`

### Expected result

1. Success reindexing for "Catalog Search"

### Actual result

`elasticsearch:5.6.3`, `elasticsearch:5.2`, and `5.0`
```
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Illegal dynamic template parameter: [match_mapping]"}],"type":"illegal_argument_exception","reason":"Illegal dynamic template parameter: [match_mapping]"},"status":400}
```

It works fine with `elasticsearch:2` docker image.

Please note, when I was trying it with `5.0` few times, I got success in running `magento indexer:reindex` once. Unfortunately, only once.
