### ISSUE TITLE
extraneous margins on product list and product list items

### ISSUE THREAD

**Issue by DanielRuf** [magento/magento2#15308]
### Preconditions

1. Magento 2.2.4

### Steps to reproduce

1. open list view of products on a page
2. inspect the list `.column.main .product-items` and one product `.products-list .product-item`

### Expected result

1. there should not be any extraneous styles

### Actual result

1. there are negative and positive margins which do nothing combined

The following code would remove it:
```css
.products-list .product-item {
    padding-left: 0;
  }
  .column.main .product-items {
    margin-left: 0;
  }
```

In general I see no sense in these margins and paddings.

See https://github.com/magento/magento2/blob/c0123f3bcaf3b3878b9b6e425f92f16468aaf87c/app/design/frontend/Magento/luma/Magento_Catalog/web/css/source/module/_listings.less#L167-L177

https://github.com/magento/magento2/blame/c0123f3bcaf3b3878b9b6e425f92f16468aaf87c/app/design/frontend/Magento/luma/Magento_Catalog/web/css/source/module/_listings.less#L167-L177

https://github.com/magento/magento2/commit/08b6a7fa8b9f10b0c73ff9c4cebc08e048b8d7a3
