### ISSUE TITLE
Magento 2.2.5 blank theme compilation error

### ISSUE THREAD

**Issue by Tofandel** [magento/magento2#16912]
Hello, after upgrading from magento 2.2.3 I had a need to recompile all less files, so I remove the view_preprocessed files and tried to recompile using a simple setup:static-content:deploy

But I got an error:
Compilation from source: vendor/magento/theme-frontend-blank/web/css/styles-m.less
variable @abs-checkout-tooltip-content-position-top is undefined in file

So I checked and indeed the variable is not defined in the file, but it is defined in vendor/magento/theme-frontend-luma/web/css/styles-m.less

So my guess is this declaration is missing in the blank theme's styles-m.less

```less
@abs-checkout-tooltip-content-position-top: {
    .lib-css(right, @checkout-tooltip-content-mobile__right);
    .lib-css(top, @checkout-tooltip-content-mobile__top);
    left: auto;

    &:before,
    &:after {
        .lib-arrow(
            @_position: top,
            @_size: @checkout-tooltip-icon-arrow__font-size,
            @_color: @checkout-tooltip-content__background-color
        );
        .lib-css(margin-top, @checkout-tooltip-icon-arrow__left);
        .lib-css(right, @indent__s);
        left: auto;
        top: 0;
    }

    &:before {
        .lib-css(border-bottom-color, @checkout-tooltip-content__border-color);
    }

    &:after {
        .lib-css(border-bottom-color, @checkout-tooltip-content__background-color);
        top: 1px;
    }
}
```
### Preconditions

1. Magento 2.2.5
2. A Magento blank theme child

### Steps to reproduce

1. Delete the cache and the preprocessed files
2. Delete the folder lib/web/design/frontend/ to erase all precompiled less files (Because why magento doesn't do this automatically on setup:upgrade is ununderstandable :angry: )
3. Run php bin/magento setup:upgrade
4. Run php bin/magento setup:di:compile
5. Run php bin/magento php bin/magento setup:static-content:deploy 

### Expected result
A compilation success

### Actual result
A compilation error:
Compilation from source: vendor/magento/theme-frontend-blank/web/css/styles-m.less
variable @abs-checkout-tooltip-content-position-top is undefined in file
