### ISSUE TITLE
Composer installation fails because of authentification

### ISSUE THREAD

**Issue by Rokko11** [magento/magento2#2545]
Hi!

I cloned the repo and executed composer install.
It works until composer tries to install "magento/composer". They ask for a username and password:

```
[ecommag1@markab html]$ composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing magento/magento-composer-installer (0.1.5)
    Downloading: 100%         

  - Installing braintree/braintree_php (2.39.0)
    Downloading: 100%         

  - Installing justinrainbow/json-schema (1.5.0)
    Downloading: 100%         

  - Installing symfony/console (v2.6.11)
    Downloading: 100%         

  - Installing symfony/process (v2.7.6)
    Downloading: 100%         

  - Installing symfony/finder (v2.7.6)
    Downloading: 100%         

  - Installing seld/jsonlint (1.3.1)
    Downloading: 100%         

  - Installing composer/composer (1.0.0-alpha10)
    Downloading: 100%         

  - Installing magento/composer (1.0.2)
    Authentication required (repo.magento.com):
      Username: 
```

When I try to access `repo.magento.com/packages.json` directly, I get the same issue.

Kind regards,
Rokko
