### ISSUE TITLE
font filetype src format in .lib-font-face mixin is not wrapped with quotation marks

### ISSUE THREAD

**Issue by emanueljacob** [magento/magento2#26888]
When using the `.lib-font-face()` mixin with an explicit `@font-format` like "woff" set, will not work. The font won't render (at least in chrome) because the filetype in the css src format is not wrapped in single quotation marks.

compiled CSS SHOULD look like this
```css
 @font-face {
        ...
        src: url('FONTPATH/FONTFILE.woff') format('woff');
        ....
    }
```

compile css how the mixin will generate it (look at format quotation marks):
```css
 @font-face {
        ...
        src: url('FONTPATH/FONTFILE.woff') format(woff);
        ....
    }
```

This could easily be fixed, by using less variable interpolation.

### Preconditions (*)
1. Magento 2.3.4 Community
2. Google Chrome  79.0.3945.130

### Steps to reproduce (*)
1. Setup a custom theme that has blank/luma as parent
2. Extend or override `/app/design/frontend/NAMESPACE/THEMENAME/web/css/source/_typography.less`
3. Add a local woff font i.e. like this:
3.a create the files in`app/design/frontend/NAMESPACE/THEMENAME/web/fonts/myfont/myfont.woff`
3.b link the static font file by adding `app/design/frontend/NAMESPACE/THEMENAME/Magento_Theme/layout/default_head_blocks.xml with the following content
```xml
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <head>
        <!-- Add custom font -->
        <font src="fonts/myfont/myfont.woff"/>
    </head>
</page>
```
4. use the `.lib-font-face()` mixin with explicit *woff* filetype set by  *using the variable* `@font-format: woff`. ie. in `_typography.less` file and 
```less
& when (@media-common = true) {
    .lib-font-face(
        @family-name:'OfficinaSerifBook',
        @font-path: '@{baseDir}fonts/myfont/myfont',
        @font-format: woff
    );
}
5. compile less files (i.e. using grunt/gulp)
```
### Expected result (*)
Because you want to use an explicit filetype (in the example "woff") the mixin from issue #4628 will be used. 

1. in the src format ([line 38](https://github.com/okorshenko/magento2/blob/05ea82c772fb6e3b2ebc4d33b43f2da387f382a4/lib/web/css/source/lib/_typography.less#L38)) the "woff" extension should be inserted *within a single quotation marks string* using variable interpolation
2. after compiling the font should be available when referenced by name in the css 

### Actual result (*)
1. in the src format ([line 38](https://github.com/okorshenko/magento2/blob/05ea82c772fb6e3b2ebc4d33b43f2da387f382a4/lib/web/css/source/lib/_typography.less#L38)) the "woff" extension will be inserted directly (not within a single quotation marks string)
2. the font is not available when referenced - or to be more concrete, it will not be rendered (instead the fallback will be used)

please see my pull request here:
https://github.com/magento/magento2/pull/26890
