### ISSUE TITLE
Unable to format Paypal's response properly 

### ISSUE THREAD

**Issue by imrankln** [magento/magento2#27456]
When trying to checkout with Paypal express checkout on Magento, it doesn't redirect to Paypal page and stays on blank page;  URL: < domain.com >/paypal/express/start/

### Preconditions (*)

1. Magento 2.3.4
2. Bug occurs when Paypal returns response 2 times.
First time _HTTP/1.1 100 Continue_
Second time _HTTP/1.1 200 Ok_

### Steps to reproduce (*)

1. Try to Checkout with Paypal express checkout

### Expected result (*)

Paypal Response (after Magento Formatting it)
```
Array(
        [TOKEN]=EC-2d0WWWWWWWWWWWWW30103
        [TIMESTAMP] => 2020-03-26T10:47:02Z
        [CORRELATIONID] => 8axxxxxx3646
        [ACK] => Success
        [VERSION] => 72.0
        [BUILD] => 54xxxxxx58
    )
```
### Actual result (*)

```
Array
    (
        [HTTP/1.1 200 OK
    Cache-Control: max-age] => 0, no-cache, no-store, must-revalidate
    Content-Length: 137
    Content-Type: text/plain; charset=utf-8
    Date: Thu, 26 Mar 2020 10:47:00 GMT
    Paypal-Debug-Id: 8axxxxxx3646
    X-Paypal-Api-Rc: 
    X-Paypal-Operation-Name: SetExpressCheckout
    X-Slr-Retry-Api: SetExpressCheckout
    
    TOKEN=EC-2d0WWWWWWWWWWWWW30103
        [TIMESTAMP] => 2020-03-26T10:47:02Z
        [CORRELATIONID] => 8axxxxxx3646
        [ACK] => Success
        [VERSION] => 72.0
        [BUILD] => 54xxxxxx58
    )
```
### Others information

This error occurs when we are getting following response from Paypal

```
HTTP/1.1 100 Continue
    
HTTP/1.1 200 OK
    Cache-Control: max-age=0, no-cache, no-store, must-revalidate
    Content-Length: 137
    Content-Type: text/plain; charset=utf-8
    Date: Thu, 26 Mar 2020 10:47:00 GMT
    Paypal-Debug-Id: 8axxxxxx3646
    X-Paypal-Api-Rc: 
    X-Paypal-Operation-Name: SetExpressCheckout
    X-Slr-Retry-Api: SetExpressCheckout
    
 TOKEN=EC%2d0WWWWWWWWWWWWW30103&TIMESTAMP=2020%2d03%2d26T10%3a47%3a02Z&CORRELATIONID=8axxxxxx3646&ACK=Success&VERSION=72%2e0&BUILD=543xxxxxx8
```
File: <root>/vendor/magento/module-paypal/Model/Api/Nvp.php:1424
Function: protected function _deformatNVP
Above function should format the response properly.
