### ISSUE TITLE
Magento2 controller_action_predispatch not working with Varnish enabled

### ISSUE THREAD

**Issue by anujeetphj** [magento/magento2#28686]
Magento  2.3.3
Varnish 6 enabled
Docker setup:

Below is my docker-compose.yml

```
version: "3.4"
services:
  web:
    build: ./
    ports:
      - "3000:80"
    volumes:
      - .:/var/www/html
    environment:
      - ENABLE_SENDMAIL=true
  db:
    image: meanbee/magento-mysql
    ports:
      - "12345:3306"
    env_file:
      - db.env
    volumes:
      - "../redcrossm2db:/var/lib/mysql"

  varnish:
    image: varnish
    #ports:
    #  - "80:80"
    depends_on:
      - web
    volumes:
      - ./varnish-magento.vcl:/etc/varnish/default.vcl
```

I am trying to implement Force Login with controller_action_predispatch observer.
Below is my code:

app/code/Vendor/Module/etc/frontend/events.xml

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Event/etc/events.xsd">
    <event name="controller_action_predispatch">
        <observer name="kernel_request_before" instance="Vendor\Module\Observer\FrontSendResponseBefore" shared="false" />
    </event>
</config>
```
app/code/Vendor/Module/Observer/FrontSendResponseBefore.php

```
<?php

namespace Vendor\Module\Observer;

use Magento\Framework\Event\Observer as EventObserver;
use Magento\Framework\Event\ObserverInterface;

class FrontSendResponseBefore implements ObserverInterface
{
    private $_helper;

    /**
    * @var \Magento\Framework\App\Response\RedirectInterface
    */
    protected $redirect;

    private $_objectManager;

    public function __construct(
        \Vendor\Module\Helper\CoreHelper $helper,
        \Magento\Framework\App\Response\RedirectInterface $redirect,
        \Magento\Framework\ObjectManagerInterface $objectmanager
    ) {
        $this->_helper = $helper;
        $this->redirect = $redirect;
        $this->_objectManager = $objectmanager;
    }

    public function execute(\Magento\Framework\Event\Observer $observer)
    {
        $actionName = $observer->getEvent()->getRequest()->getFullActionName();
        $controller = $observer->getControllerAction();

        $allowedUrls = array(
            'customer_account_login', 
            'customer_account_loginPost',
            'customer_account_logout', 
            'customer_account_logoutSuccess',
            'customer_account_forgotpassword',
            'customer_account_forgotpasswordpost',
            'customer_account_createPassword', 
            'customer_account_createpassword',
            'customer_account_resetpasswordpost'
        );

        $customerSession = $this->_objectManager->create('Magento\Customer\Model\SessionFactory')->create();

        $redirect = true;
        if (!$this->ifForceLoginEnabledForStore()) {
            $redirect = false;
        } else if (in_array($actionName, $allowedUrls)) {
            $redirect = false;
        } elseif ($customerSession->isLoggedIn()) {
            $redirect = false;
        }

        if ($redirect) {
            $this->redirect->redirect($controller->getResponse(), 'customer/account/login');
        }
    }

    private function ifForceLoginEnabledForStore()
    {
        $storeId = $this->_helper->getCurrentStoreId();

        if ($this->_helper->getConfigValue('general/general/forcelogin', $storeId) == true) {

            return true;
        }

        return false;
    }
}
```

**Expected Result:**
The pages are redirected to Login page when setting enabled

**Actual Result:**
The system does not go into the observer event at all.
