### ISSUE TITLE
.lib-font-face mixin - Fixed font formats

### ISSUE THREAD

**Issue by BenGlassAtlas** [magento/magento2#4628]
The `.lib-font-face()` mixin is not very flexible as it requires you have the font in all the formats listed (eot, woff2, woff, ttf, and svg). If your font is not available in all these formats then you will run into problems with 404 errors. 

For example the font I'm using isn't available as a Woff or Woff2 file so I can't use the `.lib-font-face()` mixin as it leaves me with several 404s:

![screen shot 2016-05-23 at 08 09 25](https://cloud.githubusercontent.com/assets/8895777/15462915/c46571b2-20bd-11e6-9d32-e0d58fec85a9.png)
## Steps to reproduce
1. Use a font that doesn't contain a Woff/Woff2 variant
2. Check the console in your browser:

``` less
// Regular Noto Sans
.lib-font-face(
    @family-name: @font-family-name__base,
    @font-path: '@{baseDir}fonts/NotoSans-Regular',
    @font-weight: 400,
    @font-style: normal
);

// Italic Noto Sans
.lib-font-face(
    @family-name: @font-family-name__base,
    @font-path: '@{baseDir}fonts/NotoSans-Italic',
    @font-weight: 400,
    @font-style: italic
);

// Bold Noto Sans
.lib-font-face(
    @family-name: @font-family-name__base,
    @font-path: '@{baseDir}fonts/NotoSans-Bold',
    @font-weight: 700,
    @font-style: normal
);
```
## Expected result
1. I'd expect to have the option to specify the font formats I'd like to us, default should be all the fonts as it currently is but the option to exclude formats would be good.

Maybe (optionally) setting a variable to false could be the answer?

``` less
.lib-font-face(
    @family-name: @font-family-name__base,
    @font-path: '@{baseDir}fonts/NotoSans-Bold',
    @font-weight: 700,
    @font-style: normal,
    @eot: false,
    @woff: false,
    @woff2: false
);
```
## Actual result
1. The mixin attempts to retrieve all the font formats which leaves 404 errors.
## Workaround

To get around this I've had to manually declare my fonts without using the mixin.

``` less
// Regular Noto Sans
@font-face {
    font-family: @font-family-name__base;
    src: url('@{baseDir}fonts/NotoSans-Regular.ttf') format('truetype');
    font-weight: 400;
    font-style: normal;
}

// Italic Noto Sans
@font-face {
    font-family: @font-family-name__base;
    src: url('@{baseDir}fonts/NotoSans-Italic.ttf') format('truetype');
    font-weight: 400;
    font-style: italic;
}

// Bold Noto Sans
@font-face {
    font-family: @font-family-name__base;
    src: url('@{baseDir}fonts/NotoSans-Bold.ttf') format('truetype');
    font-weight: 700;
    font-style: normal;
}

```

And I no longer get the 404s

![screen shot 2016-05-23 at 08 23 32](https://cloud.githubusercontent.com/assets/8895777/15463213/af172f1a-20bf-11e6-8dc5-06bc58dfa23d.png)
