### ISSUE TITLE
Style changes do not show

### ISSUE THREAD

**Issue by victorchiriac89** [magento/magento2#6214]
Magento 2.1 (github version)
php 5.6
Mysql 5.6

While building my own theme:

``` document
app/design/MyTheme/theme/registration.php
```

``` php
  <?php
  \Magento\Framework\Component\ComponentRegistrar::register(
      \Magento\Framework\Component\ComponentRegistrar::THEME,
      'frontend/MyTheme/theme',
      __DIR__
  );
```

``` document
app/design/MyTheme/theme/theme.xml
```

``` xml
  <?xml version="1.0"?>
<theme xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Config/etc/theme.xsd">
    <title>My theme</title>
    <parent>Magento/blank</parent>
</theme>
```

I added the theme and registered and deployed it and the theme works fine.

But I wanted to do overrides to the Magento_Theme module css so I added some changes here:

``` document
app/design/MyTheme/theme/Magento_Theme/web/css/source/_module.less
```

**StepX**

``` comment
Clear cache 
and/or 
remove processed css/less from root_project_dir#/pub/static/mytheme/...

and/or
root_project_dir# php bin/magento cache:clean && php bin/magento cache:flush

and/or
root_project_dir# chmod -R 777 var/ app/etc pub/static

and/or
Cleared browser cache + tried different browser

and/or
root_project_dir# chmod -R 777 pub/static var/ app/etc && php56 bin/magento setup:static-content:deploy
```

After I tried to add:

``` document
app/design/MyTheme/theme/Magento_Theme/layout/default_head_blocks.xml
```

``` xml
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
        <css src="css/styles-m.css" />
        <css src="css/styles-l.css" media="screen and (min-width: 768px)"/>
        <css src="css/print.css" media="print" />
    </head>
</page>
```

Then tried StepX again.

Then I tried adding style to theme as described in:

``` url
http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/css-topics/css-themes.html
```

``` document
app/design/MyTheme/theme/web/css/_styles.less
```

``` less
// Theme colors
@theme-light-blue:#98DDDE;
.page-header {
        .panel.wrapper {
            .lib-css(background-color, @theme-light-blue);
        }
    }
```

or

``` less
// Theme colors
@theme-light-blue:#98DDDE;
.page-header {
        .panel.wrapper {
            background: @theme-light-blue;
        }
    }
```

Then tried StepX again.

Is there any way I can update Magento_Theme/web/css/source/_module.less css, I probably did it completely wrong or there is a bug here.
